# Generated by Django 4.0.2 on 2022-02-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('oil', 'Oil'), ('grains', 'Grains'), ('cosmetics', 'Cosmetics')], max_length=100)),
                ('Quantity', models.IntegerField()),
                ('RatePerUnit', models.FloatField()),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
