# Generated by Django 4.0.2 on 2022-02-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeGrocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['-Amount']},
        ),
        migrations.AlterField(
            model_name='grocery',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='RatePerUnit',
            field=models.IntegerField(),
        ),
    ]
