# Generated by Django 4.0.2 on 2022-02-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_takegrocery_alter_grocery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={},
        ),
        migrations.AlterField(
            model_name='grocery',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
    ]
